version: "3"

services:
  app:
    build: docker/php
    ports:
      - 9001:9001
    volumes:
      - ./:/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/www.conf:/usr/local/etc/php/www.conf
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
    depends_on:
      - db
    networks:
      - internal

  mix:
    image: node:12
    working_dir: /app
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    command: npm run hot
    networks:
      - internal
  nginx:
    image: nginx:1.19
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
      - app
    networks:
      - internal
  db:
    image: mysql:8
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    env_file:
      - .env
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_RANDOM_ROOT_PASSWORD:
    networks:
      - internal
volumes:
  dbdata:
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
